config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :people do
    member do
      get :full_detail
    end
  end
  root to: 'people#index'

  namespace :api do
    namespace :v1 do
      resources :people, format: 'json' do
        collection do
          post :create_with_detail
        end
      end
      resources :details, format: 'json'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
# frozen_string_literal: true

class Detail < ApplicationRecord
  # validations
  validates :name, presence: true

  # associations
  belongs_to :person
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  # validations
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  # associations
  has_one :detail, dependent: :destroy
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

module Api
  class BaseController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_default_response_format

    private

    def set_default_response_format
      request.format = :json
    end
  end
end

app/controllers/api/v1/details_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class DetailsController < ApplicationController
      def index
        @details = Detail.all
        render json: @details
      end

      def show
        @detail = Detail.find(params[:id])
        render json: @detail
      end

      def create
        @detail = Detail.new(detail_params)

        if @detail.save
          render json: @detail, status: :created
        else
          render json: @detail.errors, status: :unprocessable_entity
        end
      end

      def update
        @detail = Detail.find(params[:id])

        if @detail.update(detail_params)
          render json: @detail
        else
          render json: @detail.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @detail = Detail.find(params[:id])
        if @detail.destroy
          render json: { status: 'Successfully destroyed', data: @detail }, status: :ok
        else
          render json: @detail.errors, status: :unprocessable_entity
        end
      end

      private

      def detail_params
        params.require(:detail).permit(:title, :name, :age, :person_id)
      end
    end
  end
end

app/controllers/api/v1/people_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PeopleController < ApplicationController
      def index
        @people = Person.all
        render json: @people
      end

      def show
        @person = Person.find(params[:id])
        render json: @person
      end

      def create
        @person = Person.new(person_params)

        if @person.save
          render json: @person, status: :created
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      def update
        @person = Person.find(params[:id])

        if @person.update(person_params)
          render json: @person
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @person = Person.find(params[:id])
        if @person.destroy
          render json: { status: 'Successfully destroyed', data: @person }, status: :ok
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      def create_with_detail
        @person = Person.new(person_params)
        @person.build_detail(detail_params)

        if @person.save
          response = { person: @person, detail: @person.detail }
          render json: response, status: :created
        else
          render json: @person.errors, status: :unprocessable_entity
        end
      end

      private

      def person_params
        params.require(:person).permit(:email)
      end

      def detail_params
        params.permit(:name, :age, :title, :phone)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def full_detail
    @person = Person.find(params[:id])

    render turbo_stream: turbo_stream.replace(
      'person_details',
      partial: 'people/detail',
      locals: { person: @person }
    )
  end

  private

  def person_params
    params.require(:person).permit(:name, :age, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/people_helper.rb
# frozen_string_literal: true

module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/people/_detail.html.erb
<%= turbo_frame_tag "person_details" do %>
  <h1 class="text-white"><%= person&.email %></h1>
  <p class="text-white">Name : <%= person&.detail&.title %> <%= person&.detail&.name %></p>
  <p class="text-white">Age : <%= person&.detail&.age %></p>
  <p class="text-white">Phone : <%= person&.detail&.phone %></p>
<% end %>

app/views/people/index.html.erb
<div class="flex h-screen">
  <!-- Left Section -->
  <div class="w-1/2 bg-blue-500 p-8">
      <!-- Content for the left section goes here -->
      <h1 class="text-white text-4xl font-bold">Email Addresses</h1>
      <p class="text-white">
      <% @people.each do |person| %>
        <%= link_to person.email, full_detail_person_path(person), remote: true %><br>
      <% end %>
      </p>
  </div>

  <!-- Right Section -->
  <div class="w-1/2 bg-green-500 p-8">
      <!-- Content for the right section goes here -->
      <h1 class="text-white text-4xl font-bold">Person Details</h1>
      <%= render partial: "detail", locals: { person: nil } %>
  </div>
</div>